# 基于python的基础镜像
FROM python:3.10-slim
# 工作目录
WORKDIR /app
# 复制所有应用程序文件到工作目录
COPY . .

#安装依赖
# RUN pip install --no-cache-dir --default-timeout=100 -i https://pypi.tuna.tsinghua.edu.cn/simple/ -r requirements.txt
RUN pip install --no-cache-dir --default-timeout=100 -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
# 添加时区环境变量，亚洲，上海
ENV TimeZone=Asia/Shanghai
# 使用软连接，并且将时区配置覆盖/etc/timezone
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

# COPY ./config.ini /app/config.ini

# CMD ["python", "/app/personal_performance_score.py"]
CMD ["python", "/app/tabpfn_ctra_new.py", "--ids", "1,2,3", "--use-multiprocessing", "--max-workers", "8"]


